/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type Clusters = ClusterLink[] | null;
export type Keywords = string[] | null;

export interface ClusterLinks {
  clusters: Clusters;
  [k: string]: unknown;
}
export interface ClusterLink {
  id: Id;
  keywords: Keywords;
  [k: string]: unknown;
}
export interface Id {
  [k: string]: unknown;
}
