/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type Title = string;
export type MemberCount = number;
export type Keywords = string[];
export type Weight = number;
export type TotalWeight = number;
export type Center = unknown[];
export type Session = number;
export type Overviews = ClusterOverview[];
export type Cursor = string | null;

export interface ClusterOverviews {
  overviews: Overviews;
  cursor: Cursor;
  [k: string]: unknown;
}
export interface ClusterOverview {
  id: Id;
  title: Title;
  member_count: MemberCount;
  keywords: Keywords;
  weight: Weight;
  total_weight: TotalWeight;
  center: Center;
  session: Session;
  [k: string]: unknown;
}
export interface Id {
  [k: string]: unknown;
}
