/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type Title = string;
export type MeetingId = string;
export type Meeting = string;
export type Speaker = string;
export type SpeakerId = string;
export type Speeches = SpeechOverview[];

export interface Discussion {
  speaker: InitalSpeaker;
  speeches: Speeches;
  [k: string]: unknown;
}
export interface InitalSpeaker {
  name: Name;
  id: Id;
  [k: string]: unknown;
}
export interface Name {
  [k: string]: unknown;
}
export interface Id {
  [k: string]: unknown;
}
export interface SpeechOverview {
  id: Id1;
  title: Title;
  meeting_id: MeetingId;
  meeting: Meeting;
  speaker: Speaker;
  speaker_id: SpeakerId;
  [k: string]: unknown;
}
export interface Id1 {
  [k: string]: unknown;
}
