/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type Keywords = string[];
export type Cursor = string | false;
export type Author = string;
export type AuthorId = string;
export type LinkTo = string[] | null;
export type LinkedCount = number;
export type Published = string;
export type Title = string;
export type PublishedList = string[] | null;
export type Keywords1 = string[];
export type IsApex = boolean;
export type House = string;
export type Session = number;
export type Comittie = string;
export type Group = string;
export type Position = string | number;
export type Nodes = NodeOverview[];
export type MemberCount = number;
export type Keywords2 = string[] | null;
export type Links = ClusterLink[];
export type Keywords3 = string[];

export interface KokkaiClusterData {
  id: Id;
  keywords: Keywords;
  members: NodeOverviews;
  member_count: MemberCount;
  links: Links;
  session: Session1;
  before_cluster: KokkaiClusterLink | null;
  after_cluster: KokkaiClusterLink | null;
  [k: string]: unknown;
}
export interface Id {
  [k: string]: unknown;
}
export interface NodeOverviews {
  cursor: Cursor;
  nodes: Nodes;
  [k: string]: unknown;
}
export interface NodeOverview {
  id: Id1;
  author: Author;
  author_id: AuthorId;
  link_to: LinkTo;
  linked_count: LinkedCount;
  published: Published;
  title: Title;
  published_list: PublishedList;
  keywords: Keywords1;
  is_apex: IsApex;
  house: House;
  session: Session;
  comittie: Comittie;
  group: Group;
  position: Position;
  [k: string]: unknown;
}
export interface Id1 {
  [k: string]: unknown;
}
export interface ClusterLink {
  id: Id2;
  keywords: Keywords2;
  [k: string]: unknown;
}
export interface Id2 {
  [k: string]: unknown;
}
export interface Session1 {
  [k: string]: unknown;
}
export interface KokkaiClusterLink {
  id: Id3;
  session: Session2;
  keywords: Keywords3;
  [k: string]: unknown;
}
export interface Id3 {
  [k: string]: unknown;
}
export interface Session2 {
  [k: string]: unknown;
}
