/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type Cursor = string | false;
export type Data = string;
export type Author = string;
export type AuthorId = string;
export type LinkTo = string[] | null;
export type Published = string;
export type Title = string;
export type PublishedList = string[];
export type Keywords = string[];
export type House = string;
export type Session = number;
export type Position = string | number;
export type Nodes = NodeOverview[];
export type Cursor1 = string | false;

export interface LinkFrom {
  list: NodeOverviews;
  cursor: Cursor1;
  [k: string]: unknown;
}
export interface NodeOverviews {
  cursor: Cursor;
  nodes: Nodes;
  [k: string]: unknown;
}
export interface NodeOverview {
  id: Id;
  data: Data;
  author: Author;
  author_id: AuthorId;
  link_to: LinkTo;
  published: Published;
  title: Title;
  published_list: PublishedList;
  keywords: Keywords;
  house: House;
  session: Session;
  position: Position;
  [k: string]: unknown;
}
export interface Id {
  [k: string]: unknown;
}
