/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type Session = number;
export type Issue = number;
export type Name = string;
export type House = string;

export interface MeetingOveriew {
  id: Id;
  session: Session;
  issue: Issue;
  name: Name;
  house: House;
  [k: string]: unknown;
}
export interface Id {
  [k: string]: unknown;
}
