/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type Session = number;
export type Issue = number;
export type Name = string;
export type Url = string;
export type Pdf = string;
export type HeaderText = string;
export type Moderators = {
  [k: string]: unknown;
}[];
export type ModeratorIds = string[];
export type Keywords = string[];
export type House = string;

export interface MeetingSingle {
  id: Id;
  session: Session;
  issue: Issue;
  name: Name;
  url: Url;
  pdf: Pdf;
  header_text: HeaderText;
  moderators: Moderators;
  moderator_ids: ModeratorIds;
  keywords: Keywords;
  house: House;
  [k: string]: unknown;
}
export interface Id {
  [k: string]: unknown;
}
