/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type Session = number;
export type Issue = number;
export type Name = string;
export type Url = string;
export type Pdf = string;
export type HeaderText = string;
export type Moderators = {
  [k: string]: unknown;
}[];
export type ModeratorIds = string[];
export type Keywords = string[];
export type House = string;
export type Title = string;
export type MeetingId = string;
export type Meeting = string;
export type Speaker = string;
export type SpeakerId = string;
export type Speeches = SpeechOverview[];
export type Discussions = Discussion[];

export interface MeetingData {
  data: MeetingSingle;
  discussions: Discussions;
  [k: string]: unknown;
}
export interface MeetingSingle {
  id: Id;
  session: Session;
  issue: Issue;
  name: Name;
  url: Url;
  pdf: Pdf;
  header_text: HeaderText;
  moderators: Moderators;
  moderator_ids: ModeratorIds;
  keywords: Keywords;
  house: House;
  [k: string]: unknown;
}
export interface Id {
  [k: string]: unknown;
}
export interface Discussion {
  speaker: InitalSpeaker;
  speeches: Speeches;
  [k: string]: unknown;
}
export interface InitalSpeaker {
  name: Name1;
  id: Id1;
  [k: string]: unknown;
}
export interface Name1 {
  [k: string]: unknown;
}
export interface Id1 {
  [k: string]: unknown;
}
export interface SpeechOverview {
  id: Id2;
  title: Title;
  meeting_id: MeetingId;
  meeting: Meeting;
  speaker: Speaker;
  speaker_id: SpeakerId;
  [k: string]: unknown;
}
export interface Id2 {
  [k: string]: unknown;
}
