/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type Cursor = string | false;
export type Author = string;
export type AuthorId = string;
export type LinkTo = string[] | null;
export type LinkedCount = number;
export type Published = string;
export type Title = string;
export type PublishedList = string[] | null;
export type Keywords = string[];
export type IsApex = boolean;
export type House = string;
export type Session = number;
export type Comittie = string;
export type Group = string;
export type Position = string | number;
export type Nodes = NodeOverview[];

export interface NodeOverviews {
  cursor: Cursor;
  nodes: Nodes;
  [k: string]: unknown;
}
export interface NodeOverview {
  id: Id;
  author: Author;
  author_id: AuthorId;
  link_to: LinkTo;
  linked_count: LinkedCount;
  published: Published;
  title: Title;
  published_list: PublishedList;
  keywords: Keywords;
  is_apex: IsApex;
  house: House;
  session: Session;
  comittie: Comittie;
  group: Group;
  position: Position;
  [k: string]: unknown;
}
export interface Id {
  [k: string]: unknown;
}
