/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type Name = string;
export type Group = string;
export type Position = string;
export type Session = number;
export type Role = string;
export type House = string;
export type Comittie = string;

export interface SpeakerSingle {
  id: Id;
  name: Name;
  group: Group;
  position: Position;
  session: Session;
  role: Role;
  house: House;
  comittie: Comittie;
  [k: string]: unknown;
}
export interface Id {
  [k: string]: unknown;
}
