/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type MeetingId = string;
export type Meeting = string;
export type ResponseTo = string | null;
export type ResponseFrom = string | null;
export type DiscussionId = string;
export type Url = string;
export type Order = number;
export type Session = number;
export type Issue = number;
export type House = string;
export type Body = string;
export type Title = string;
export type MemberCount = number;
export type Keywords = string[];
export type Weight = number;
export type TotalWeight = number;
export type Center = unknown[];
export type Session1 = number;
export type Overviews = ClusterOverview[];
export type Cursor = string | null;
export type Discussion = SpeechOverview[] | null;
export type Title1 = string;
export type MeetingId1 = string;
export type Meeting1 = string;
export type Speaker = string;
export type SpeakerId = string;
export type Keywords1 = string[] | null;
export type Name = string;
export type Group = string;
export type Position = string;
export type Session2 = number;
export type Role = string;
export type House1 = string;
export type Comittie = string;
export type Cursor1 = string | false;
export type Author = string;
export type AuthorId = string;
export type LinkTo = string[] | null;
export type LinkedCount = number;
export type Published = string;
export type Title2 = string;
export type PublishedList = string[] | null;
export type Keywords2 = string[];
export type IsApex = boolean;
export type House2 = string;
export type Session3 = number;
export type Comittie1 = string;
export type Group1 = string;
export type Position1 = string | number;
export type Nodes = NodeOverview[];
export type LinkTo1 = NodeOverview[];

export interface SpeechData {
  speech: SpeechSingle;
  clusters: ClusterOverviews;
  discussion?: Discussion;
  keywords: Keywords1;
  speaker: SpeakerSingle;
  link_from: NodeOverviews;
  link_to: LinkTo1;
  [k: string]: unknown;
}
export interface SpeechSingle {
  id: Id;
  meeting_id: MeetingId;
  meeting: Meeting;
  response_to: ResponseTo;
  response_from: ResponseFrom;
  discussion_id: DiscussionId;
  url: Url;
  order: Order;
  session: Session;
  issue: Issue;
  house: House;
  body: Body;
  [k: string]: unknown;
}
export interface Id {
  [k: string]: unknown;
}
export interface ClusterOverviews {
  overviews: Overviews;
  cursor: Cursor;
  [k: string]: unknown;
}
export interface ClusterOverview {
  id: Id1;
  title: Title;
  member_count: MemberCount;
  keywords: Keywords;
  weight: Weight;
  total_weight: TotalWeight;
  center: Center;
  session: Session1;
  [k: string]: unknown;
}
export interface Id1 {
  [k: string]: unknown;
}
export interface SpeechOverview {
  id: Id2;
  title: Title1;
  meeting_id: MeetingId1;
  meeting: Meeting1;
  speaker: Speaker;
  speaker_id: SpeakerId;
  [k: string]: unknown;
}
export interface Id2 {
  [k: string]: unknown;
}
export interface SpeakerSingle {
  id: Id3;
  name: Name;
  group: Group;
  position: Position;
  session: Session2;
  role: Role;
  house: House1;
  comittie: Comittie;
  [k: string]: unknown;
}
export interface Id3 {
  [k: string]: unknown;
}
export interface NodeOverviews {
  cursor: Cursor1;
  nodes: Nodes;
  [k: string]: unknown;
}
export interface NodeOverview {
  id: Id4;
  author: Author;
  author_id: AuthorId;
  link_to: LinkTo;
  linked_count: LinkedCount;
  published: Published;
  title: Title2;
  published_list: PublishedList;
  keywords: Keywords2;
  is_apex: IsApex;
  house: House2;
  session: Session3;
  comittie: Comittie1;
  group: Group1;
  position: Position1;
  [k: string]: unknown;
}
export interface Id4 {
  [k: string]: unknown;
}
