# Copyright 2021 Google LLC


runtime: python312

handlers:
- url: /
  script: auto
  login: admin
- url: /resume
  script: auto
  login: admin
- url: /.+
  script: auto
 

automatic_scaling:
  max_instances: 1