/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type FromCluster = string;
export type ToCluster = string;

export interface ClusterLink {
  from_cluster: FromCluster;
  to_cluster: ToCluster;
  [k: string]: unknown;
}
