/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type TextId = string;
export type LinkedCount = number;
export type Published = string;
export type Position = number;

export interface ClusterMember {
  cluster_id: ClusterId;
  text_id: TextId;
  linked_count: LinkedCount;
  published: Published;
  position: Position;
  [k: string]: unknown;
}
export interface ClusterId {
  [k: string]: unknown;
}
