/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type Session = number;
export type Issue = number;
export type Name = string;
export type Start = string;
export type End = string;
export type ResponseFrom = string;
export type Url = string;
export type Pdf = string;
export type HeaderText = string;
export type Moderators = string[];
export type ModeratorIds = string[];

export interface Meeting {
  session: Session;
  issue: Issue;
  name: Name;
  start: Start;
  end: End;
  response_from: ResponseFrom;
  url: Url;
  pdf: Pdf;
  header_text: HeaderText;
  moderators: Moderators;
  moderator_ids: ModeratorIds;
  [k: string]: unknown;
}
