/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type MeetingId = string;
export type Text = string;
export type Speaker = string;
export type SpeakerId = string;
export type ResponseTo = string;
export type ResponseFrom = string;
export type DiscussionId = string;
export type Url = string;
export type Order = number;
export type Session = number;

export interface Speech {
  meeting_id: MeetingId;
  text: Text;
  speaker: Speaker;
  speaker_id: SpeakerId;
  response_to: ResponseTo;
  response_from: ResponseFrom;
  discussion_id: DiscussionId;
  url: Url;
  order: Order;
  session: Session;
  [k: string]: unknown;
}
